-- AlterTable
ALTER TABLE `tarefa` ADD COLUMN `dataDeCriacao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `dataDeParaConclusao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
